import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import getUser from "@/lib/getUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  let loggedIn: boolean;
  if(user) {
    loggedIn = true;
  } else {
    loggedIn = false;
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-neutral-800`}
      >
        <Navbar loggedIn={loggedIn} />
        <div className="pt-20 min-h-screen w-full bg-linear-to-br from-red-100 via-purple-100 to-blue-100">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
